http_server:
  host: "localhost"
  port: 8080

logger:
  level: "debug"
  format: "text"
  output: "stdout"

db:
  host: "localhost"
  port: 5432
  user: "gophkeeper"
  password: "gophkeeper"
  database: "gophkeeper"
  sslmode: "disable"

auth:
  jwt_secret: "my_super_secret_key"

cache:
  cache1:
    max-items: 100
    item-size: 64
  cache2:
    max-items: 200
    item-size: 80
