http_server:
  host: "http://localhost"
  port: 8080

logger:
  level: "debug"
  format: "text"
  output: "./logs/gophkeeper.log"

cache:
  cache1:
    max-items: 100
    item-size: 64
  cache2:
    max-items: 200
    item-size: 80
